extend-exclude = [
    "numpy/__config__.py",
    "numpy/distutils",
    "numpy/typing/_char_codes.py",
    "numpy/typing/tests/data",
    "spin/cmds.py",
    # Submodules.
    "doc/source/_static/scipy-mathjax",
    "vendored-meson/meson",
    "numpy/fft/pocketfft",
    "numpy/_core/src/umath/svml",
    "numpy/_core/src/npysort/x86-simd-sort",
    "numpy/_core/src/highway",
    "numpy/_core/src/common/pythoncapi-compat",
]

line-length = 88

[lint]
preview = true
extend-select = [
    "C4",
    "LOG",
    "G",
    "PIE",
    "TID",
    "FLY",
    "E",
    "W",
    "PGH",
    "PLE",
    "UP",
]
ignore = [
    "C408",   # Unnecessary `dict()` call (rewrite as a literal)
    "PIE790", # Unnecessary `pass` statement
    "E241",   # Multiple spaces after comma
    "E265",   # Block comment should start with `# `
    "E266",   # Too many leading `#` before block comment
    "E302",   # TODO: Expected 2 blank lines, found 1
    "E402",   # Module level import not at top of file
    "E712",   # Avoid equality comparisons to `True` or `False`
    "E721",   # TODO: Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance check
    "E731",   # Do not assign a `lambda` expression, use a `def`
    "E741",   # Ambiguous variable name
    "F403",   # `from ... import *` used; unable to detect undefined names
    "F405",   # may be undefined, or defined from star imports
    "F821",   # Undefined name
    "F841",   # Local variable is assigned to but never used
    "UP015",  # Unnecessary mode argument
    "UP031",  # TODO: Use format specifiers instead of percent format
]

[lint.per-file-ignores]
"test*.py" = ["E201", "E714"]
"benchmarks/*py" = ["E501"]
"numpy/_build_utils/*py" = ["E501"]
"numpy/__init__.py" = ["E501"]
"numpy/_core/**" = ["E501"]
"numpy/core/**" = ["E501"]
"numpy/_typing/*py" = ["E501"]
"numpy/lib/*py" = ["E501"]
"numpy/linalg/*py" = ["E501"]
"numpy/ma/*py" = ["E501"]
"numpy/polynomial/*py" = ["E501"]
"numpy/tests/*py" = ["E501"]
"numpy/random/*py" = ["E501"]
"numpy*pyi" = ["E501"]
"numpy/f2py/*py" = ["E501"]
"__init__.py" = ["F401", "F403", "F405"]
"__init__.pyi" = ["F401"]
"numpy/_core/defchararray.py" = ["F403", "F405"]
"numpy/_core/multiarray.py" = ["F405"]
"numpy/_core/numeric.py" = ["F403", "F405"]
"numpy/_core/umath.py" = ["F401", "F403", "F405"]
"numpy/f2py/capi_maps.py" = ["F403", "F405"]
"numpy/f2py/crackfortran.py" = ["F403", "F405"]
"numpy/f2py/f90mod_rules.py" = ["F403", "F405"]
"numpy/ma/core.pyi" = ["F403", "F405"]
"numpy/matlib.py" = ["F405"]
"numpy/matlib.pyi" = ["F811"]
