name: BLAS tests (Linux)

# This file is meant for testing different BLAS/LAPACK flavors and build
# options on Linux. All other yml files for Linux will only test without BLAS
# (mostly because that's easier and faster to build) or with the same 64-bit
# OpenBLAS build that is used in the wheel jobs.
#
# Jobs and their purpose:
#
#   - openblas32_stable_nightly:
#         Uses the 32-bit OpenBLAS builds, both the latest stable release
#         and a nightly build.
#
# TODO: coverage here is limited, we should add non-OpenBLAS libraries and
#       exercise the BLAS-related build options (see `meson_options.txt`).

on:
  pull_request:
    branches:
      - main
      - maintenance/**

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  openblas32_stable_nightly:
    if: "github.repository == 'numpy/numpy'"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        USE_NIGHTLY_OPENBLAS: [false, true]
    env:
      USE_NIGHTLY_OPENBLAS: ${{ matrix.USE_NIGHTLY_OPENBLAS }}
    name: "Test Linux (${{ matrix.USE_NIGHTLY_OPENBLAS && 'nightly' || 'stable' }} OpenBLAS)"
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r build_requirements.txt
        # Install OpenBLAS
        set -xe
        if [[ $USE_NIGHTLY_OPENBLAS == "true" ]]; then
          target=$(python tools/openblas_support.py --nightly)
        else
          target=$(python tools/openblas_support.py)
        fi
        sudo cp -r $target/lib/* /usr/lib
        sudo cp $target/include/* /usr/include

    - name: Build
      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      env:
        TERM: xterm-256color
      run:
        spin build -- --werror

    - name: Check build-internal dependencies
      run:
        ninja -C build -t missingdeps

    - name: Check installed test and stub files
      run:
        python tools/check_installed_files.py $(find ./build-install -path '*/site-packages/numpy')

    - name: Test
      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      env:
        TERM: xterm-256color
        LD_LIBRARY_PATH: "/usr/local/lib/"  # to find libopenblas.so.0

      run: |
        pip install pytest pytest-xdist hypothesis typing_extensions
        spin test -j auto
